### ISSUE TITLE
Лабораторная работа №2

### ISSUE THREAD

**Issue by Detect1ve** [Detect1ve/TRPO#1]
Выполнил: Гринь Николай.
to: @evgeny-p

**Comment by evgeny-p** [comment]
1. Коэффициенты уравнения, дискриминант и корни могут быть числами с плавающей точкой.
2. Код, отвечающий за случай, когда есть один или два корня, разорван на два блока:
   1. Первый блок. Проверяется, что корни есть. Вычисляются.
   2. Затем проверяется, что корней нет. Возврат.
   3. Второй блок: идет продолжение первой ветки: вывод корней.
      Исправить можно, вынеся проверку на отсутствие корней вперед. Т.к. при отсутствии корней будет выполнено завершение приложения, то для их вычисления не обязательно проверять условие `d >= 0`.
3. Пропущен пробел между оператором `if` и открывающей круглой скобкой.

**Comment by evgeny-p** [comment]
Принято.

На будущее:
1. Обсуждение одной задачи лучше вести в рамках одного issue.
2. На паре обсуждали, что один коммит должен содержать только одну логическую порцию изменений.
